Table users{
    id int [pk]
    name varchar
}

Table notes{
    id int [pk]
    //Un uno a muchos
    user_id int [ref: > users.id]
    title varchar
    content text
    created_at timestamp
    updated_at timestamp
}

Table tags{
    id int [pk]
    name varchar
    slug varchar [unique]
    created_at timestamp
    updated_at timestamp
}

table note_tag{
    note_id int [ref: > notes.id]
    tag_id int [ref: > tags.id]
    created_at timestamp
    updated_at timestamp
    indexes {
        (note_id, tag_id) [unique]
    }

}
